### PR TITLE
fix: publication and workspace cards on homepage are missing the rel="noopener noreferrer"attribute (#3336)

### LINKED ISSUE #3336: Publication card on homepage is missing the rel="noopener noreferrer"attribute
image

image

### PR DESCRIPTION
**Pull request by frano-m**
Closes #3336.

image

image

### CODE REVIEW

File: components/Home/components/Section/components/SectionDatasets/components/Datasets/components/Cards/cards.tsx
Comment (frano-m) [inline components/Home/components/Section/components/SectionDatasets/components/Datasets/components/Cards/cards.tsx:1]: Added `noopener noreferrer` to Datasets.

File: components/Home/components/Section/components/SectionDatasets/sectionDatasets.tsx [hunk 1]
```diff
@@ -35,7 +36,10 @@ export const SectionDatasets = ({
           <NLink href={CONSORTIA_ROADMAP} legacyBehavior passHref>
             <ButtonSecondary href="passHref">Consortia Roadmap</ButtonSecondary>
           </NLink>
-          <ButtonSecondary href={`${portalURL}${EXPLORE_DATASETS}`}>
+          <ButtonSecondary
```
Comment (frano-m) [inline components/Home/components/Section/components/SectionDatasets/sectionDatasets.tsx:39]: Added `noopener noreferrer` to Explore Datasets.

File: components/Home/components/Section/components/SectionPublications/sectionPublications.tsx [hunk 2]
```diff
@@ -21,6 +24,7 @@ export const SectionPublications = (): JSX.Element => {
             <Button
               color="primary"
               href={ADD_PUBLICATION}
+              rel={REL_ATTRIBUTE.NO_OPENER_NO_REFERRER}
```
Comment (frano-m) [inline components/Home/components/Section/components/SectionPublications/sectionPublications.tsx:27]: Added `noopener noreferrer` to "Add Publication" link.

File: components/Layout/components/Content/components/ContentEnd/components/Contribute/contribute.tsx [hunk 3]
```diff
@@ -29,6 +32,7 @@ export const Contribute = ({ slug }: ContributeProps): JSX.Element => {
         disabled={slug?.length === 0}
         href={getGitHubUrl(slug)}
         startIcon={<CodePullRequestIcon color="inkLight" />}
+        rel={REL_ATTRIBUTE.NO_OPENER_NO_REFERRER}
```
Comment (frano-m) [inline components/Layout/components/Content/components/ContentEnd/components/Contribute/contribute.tsx:35]: Added `noopener noreferrer` to "Make a contribution" link.

File: components/Layout/components/Header/components/CallToAction/callToAction.styles.ts
Comment (frano-m) [inline components/Layout/components/Header/components/CallToAction/callToAction.styles.ts:1]: Unused.

File: components/Overview/components/Publications/components/Button/button.tsx [hunk 4]
```diff
@@ -1,11 +1,15 @@
...
+  REL_ATTRIBUTE,
+} from "@databiosphere/findable-ui/lib/components/Links/common/entities";
 import { Button as PrimaryButton } from "./button.styles";
 
 export const Button = (): JSX.Element => {
   return (
     <PrimaryButton
       color="primary"
       href="https://github.com/anvilproject/anvil-portal/issues/new/?template=add-a-publication.md"
+      rel={REL_ATTRIBUTE.NO_OPENER_NO_REFERRER}
```
Comment (frano-m) [inline components/Overview/components/Publications/components/Button/button.tsx:12]: Added `noopener noreferrer` to "Add Your Publication".
